### PR TITLE
First pass at adding CI

### PR DESCRIPTION
**Pull request by adelevie**

### CODE REVIEW

**Comment by adelevie** [comment]
@benbalter, am I not using `html-proofer` properly?

**Comment by benbalter** [comment]
It looks close to right, does it work locally? Perhaps @gjtorikian can help as well.

**Comment by adelevie** [comment]
It just seemed to report a lot of false positives. If nothing jumped out at you, it's probably on our end. Thanks!.

**Comment by gjtorikian** [comment]
Looks almost certainly to be related to `baseurl` (I didn't clone the repo down, just a hunch). I see that you set `url`, but not `baseurl`.

**Comment by adelevie** [comment]
Thanks, @gjtorikian!

**Pull request closed without merging**
