### PR TITLE
Update and clean up hidden content page

### PR DESCRIPTION
**Pull request by shawnbot**
[😎  preview on Federalist](https://federalist.18f.gov/preview/18f/accessibility/update-hidden-content/hidden-content/)

This is an update to the [hidden content page](https://pages.18f.gov/accessibility/hidden-content/) that simplifies, tidies up, and edits some of the copy to better match the guidance of our [content guide](https://pages.18f.gov/content-guide/). Also:

1. Reduce the multi-line CSS `display: none` code samples with an inline snippet
1. Replace the unwieldy HTML table to a markdown table, and enable support for markdown tables in the Jekyll config
1. Rename `hiddencontent.md` to `hidden-content.md`

### CODE REVIEW

**Comment by ghost** [comment]
I found 1 accessibility errors:
```
'http://localhost:4000/hidden-content/ | serious | Data tables should be marked up properly | ["#main > table"]'
```

**Comment by nickbristow** [comment]
@shawnbot can you mark `scope='col'` on the table?

**Comment by selfthinker** [comment]
As far as I know, most AT don't interpret the `scope` attribute at all. Furthermore, I don't think it is required for simple tables, so would rather file a bug report for accesslint or aXe. Unless it's one of those issues that is different in Section 508 from WCAG?

See also https://www.w3.org/TR/WCAG20-TECHS/H63.html
> For simple tables that have the headers in the first row or column then it is sufficient to simply use the TH elements without scope.

**Comment by nickbristow** [comment]
@selfthinker I think you are correct in that most screen readers wouldn't have an issue reading a simple table properly marked with `<th>`. 

Using scope explicitly defines the relationship and certain testing guidelines for 508 require the scope attribute.

**Pull request closed without merging**
