### PR TITLE
Fix typos and formatting

### PR DESCRIPTION
**Pull request by selfthinker**
This fixes a few typos, grammatical errors and wrong formatting. It should all be pretty straightforward.
I found a few more things but as they are less straightforward, I will open new PRs for them.

### CODE REVIEW

**Comment by selfthinker** [comment]
Any reason why this hasn't been merged? I thought this would be one of the most straightforward PRs. It did catch what was merged in #228 and #230.
I would fix the conflict that those created, if only I had an inkling if this had a chance of being merged or not?

**Comment by selfthinker** [comment]
And what was fixed in #233 was already fixed in here as well. I feel personally offended. :'(

**Comment by randyhart** [comment]
@nkkl  re-upping this one.  I'm out of my element in trying to resolve conflicts on GitHub.  Any ideas on who could take the lead on this one?

**Comment by nkkl** [comment]
@randyhart want to hop on a call for 5 minutes? I can show you how to do this, so that you know in the future. :)

**Pull request merged**
