### PR TITLE
Fix AccessLint errors

### PR DESCRIPTION
**Pull request by maya**
Fixes https://github.com/18F/accessibility/issues/166

How do we skip errors that are intentional?

### CODE REVIEW

**Comment by maya** [comment]
Hmm.. where is AccessLint? Got this error: `Failed to comment: CI_PULL_REQUEST is missing.` @gemfarmer

**Comment by gemfarmer** [comment]
@maya 🤔 hmm that is a new one for me. I'll go ask in the accesslint channel. It is possible that it is a new spec

**Comment by gemfarmer** [comment]
@maya I see why it isn't commenting. It needs [this info](https://github.com/accesslint/accesslint-ci/blob/de6aa887ee3584175728bd34ee4b6fe3777c844d/lib/accesslint/ci/commenter.rb#L42) to comment properly, and for whatever reason it isn't receiving circleCI's [`CI_PULL_REQUEST` variable](
https://circleci.com/docs/environment-variables/#build-details)

**Comment by maya** [comment]
@gemfarmer any updates on why it isn't receiving circleCI's CI_PULL_REQUEST variable?

**Comment by gemfarmer** [comment]
@maya no new news. I left a comment on the accesslint slack, but haven't received a response. I haven't seen anything acting up on 18f site 😕 


@ckundo, have you seen other issues with Circle's `CI_PULL_REQUEST` environment variable?

**Comment by maya** [comment]
@gemfarmer FYI AccessLint worked on another PR: https://github.com/18F/accessibility/pull/168#issuecomment-271672466

**Comment by maya** [comment]
@gemfarmer it works now! :)

**Pull request merged**
