### PR TITLE
Use guides_style_18f gem

### PR DESCRIPTION
**Pull request by mbland**
cc: @nickbristow

### CODE REVIEW

**Comment by nickbristow** [comment]
@mbland it looks like this would take away the custom javascript i have on certain pages

**Comment by mbland** [comment]
Can you point me to which scripts, and which pages? I'm not seeing anything leap out at me; notice that the scripts removed by this PR are now encapsulated in https://github.com/18F/guides-style/tree/master/assets/js.

Also, you/I can add page-specific scripts back by adding them to a `scripts:` list in the front matter of the page. (Also, we can add a `scripts:` list to `_config.yml` to add them to every page.)

**Comment by adelevie** [comment]
I think `_includes/scripts.html` needs to remain, but all other JS can be removed. Confirm this, @nickbristow?

**Comment by nickbristow** [comment]
yeah these should be moved out of the include scripts file, but they are needed. 
```
-{% if page.title == "Keyboard Access" %}
-<script type="text/javascript">
-	$(document).ready(function(){
-		$('.moveFocus').on('focus',function(){
-			$('.keyboardTrap:first').focus();
-		});
-		$('.keyboardTrap').click(function(){
-			$('.moveFocus').each(function(){
-				$(this).remove();
-			});
-		});
-	});
-</script>
-{% endif %}
-
-{% if page.title == "Flashing" %}
-<script type="text/javascript">
-	$(document).ready(function(){
-		var blinking = false,
-			interval,
-			$blink = $('.blink');
-		$('#blinkbutton').click(function(){
-			if (!blinking){
-				$('#blinkbutton').html('Click to stop blinking');
-				interval = setInterval(function(){
-					$blink.toggle();
-				},200);
-				blinking = true;
-			}
-			else
-			{
-				clearInterval(interval);
-				$('#blinkbutton').html('Click to see non-compliant flashing');
-				$blink.hide();
-				blinking = false;
-			}
-		});
-
-	});
-</script>
-{% endif %}
-{% if page.title == "Time Outs" %}
-<script type="text/javascript">
-	$(document).ready(function(){
-		var timer;
-		$('#pForm input').on('input',function(){
-			if (timer)
-				clearTimeout(timer);
-			timer = setTimeout(function(){
-				var c = confirm('Would you like more time to complete the form?'),
-				time;
-				if(c == true)
-					clearTimeout(timer);
-				else
-					$('#pForm').trigger('reset');
-			}, 2000);
-		});
-	});
-</script>
-{% endif %} 
```

**Comment by adelevie** [comment]
Wow, look at that timing.

**Comment by mbland** [comment]
D'oh! I even noticed that before, when I was setting up 18F/guides-style... I'll push a fix.

**Comment by mbland** [comment]
OK, pushed a new commit to restore the JavaScript to the specific pages that need it. PTAL? (If you run it locally, note you'll need to comment out the `asset_root_` attribute in `_config.yml`.)

**Pull request merged**
