### PR TITLE
Add primary nav + homepage link updates

### PR DESCRIPTION
**Pull request by iamjolly**
With this update:
- Added a "primary nav" with links to:
  - Accessibility for Teams
  - Section 508
  - 18F home
- Added some tools/resources links to home page

### CODE REVIEW

**Comment by iamjolly** [comment]
Preview here: https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/accessibility/add-primary-nav/

**Review by Jacklynn — COMMENTED** [review]
Wow! Thanks for your work on this! I actually think that the 508 & accessibility for teams link might work better in the Resources > Government Sites and tutorials section. I think your 508 link could replace the one on their now too. The 18F home page is already in the footer.

I think having these links in the primary nav in this way may be misleading, they make it look they are parts of the guide when they're actually taken to different website a user can't navigate back from (besides the browser back button). I feel bad knowing you did all this work though!

**Comment by iamjolly** [comment]
@Jacklynn - Thanks for this feedback! Making these changes is no problem. I was wondering about whether or not those links were appropriate in the primary nav, so this is good confirmation on what I was questioning myself. I'll remove them, and move them into the places you suggested. 

I'll update this PR and ping you when it's ready.

**Comment by iamjolly** [comment]
OK @Jacklynn, this should be ready now... https://cg-06ab120d-836f-49a2-bc22-9dfb1585c3c6.app.cloud.gov/preview/18f/accessibility/add-primary-nav/. When you have a chance, do you mind giving it another look? Thank you!

**Review by Jacklynn — APPROVED** [review]
Thanks!

**Pull request merged**
