### PR TITLE
Update checklist.md

### PR DESCRIPTION
**Pull request by egamble23**
Suggestion for adding Google tools accessibility checklist as a resource on this page.

### CODE REVIEW

**Comment by egamble23** [comment]
This is related to TLC Crew issue #180 https://github.com/18F/TLC-crew/issues/180

**Review by jasnakai — APPROVED** [review]
LGTM!

**Comment by jasnakai** [comment]
I believe the pa11y error has to do with this issue: https://stackoverflow.com/questions/72331753/ruby-and-rails-github-action-exit-code-16

**Comment by egamble23** [comment]
Thank you!

**Comment by egamble23** [comment]
Hi @jasnakai , is it okay for me to merge this PR? 

Or please let me know if there ought to be any other reviews. Thanks!

**Pull request merged**
