### PR TITLE
updated heading language

### PR DESCRIPTION
**Pull request by nickbristow**

### CODE REVIEW

**Comment by maya** [comment]
@nickbristow I think we should use something like this:

When laying out a page, headings provide a semantic way to lay out sections of content. A heading element briefly describes the topic of the section it introduces. Heading elements are used by users of AT to navigate a page quickly and to understand the structure of a page. Also see [Landmarks](../landmarks/).

When using heading elements, reserve the `<h1>` element for the page title. On the home page, this is usually the title of the site and on other pages, this may be the page title. Use the `<h1>` tag once per page—assistive technology is unable to read multiple `<h1>`s on a single page. Other heading levels may be used more than once following document outline order.

For sub sections, use `<h2>` to `<h6>` in document outline order. `<h1>` is the most important and `<h6>` is the least. Avoid skipping headings. Avoid breaking document outline order (you may go from `<h1>` to `<h3>`, but never `<h3>` to `<h1>`).

For logos that are text-based, use `<em>` tags. 

***

I didn't understand:
>If your logo is acting as the main heading of the page, use a `sr-only` `<h1>` tag for screen reader users.

When would you not want your logo to display. Can you expand that use case so it's clearer?

**Comment by nickbristow** [comment]
@maya this got lost while i was out of town. 

Your writing is good. Going to merge.

**Comment by nickbristow** [comment]
@maya oh i should say i put in your copy. Not just that it was good and i was merging anyway...

**Comment by maya** [comment]
🎉 👯

**Pull request merged**
