### PR TITLE
Update headings.md

### PR DESCRIPTION
**Pull request by nickbristow**
Clarified <em> logo recommendation

### CODE REVIEW

**Comment by selfthinker** [comment]
I find this section more confusing now...

> For image logos that are acting as the main heading of the page

This confuses me because I interpret "the main heading of the page" as the page title. And usually there is no logo in that. As the page also says "reserve the `<h1>` element for the page title", this is probably just a typo?

> add an `<h1>` element for its text and use a sr-only rule
> For text-based logos that are not acting as the main header

So, image logos should be in a heading and text-based logos should not? I don't think that was what you meant to say but that's how I read this.
Regarding the reference to "a sr-only rule", although this would work, I don't think any hidden text is necessary for an image if you have the `alt` attribute set properly.

> we recommend using the emphasis tag `<em>`

I think this section is generally conflating three things:

## What is important for accessibility?

For accessibility it is only important that there is one `h1` per page (ish). How that is solved only matters in so much that the structure of the page should make sense. 

## What are good practice examples?

In practice that means you should either **make the site title the `h1` and the page title an `h2`**. That is what you're doing in your template right now.

Or you can **make the page title the `h1`** (which can be the site title on the homepage). That is what you're describing within your guide.
Then the site title should either be an `h2` or just a `p` (or an `em` or a `strong` or whatever), depending if you buy into not having any headings above the `h1` or not (which is debatable and mostly a matter of preference). It is only important to stay consistent and to let the heading structure make sense.

There can only be two examples of where the `h1` goes (as far as I'm aware). (Those two examples are also used in the W3C's Web Accessibility Tutorial about [headings and page structure](https://www.w3.org/WAI/tutorials/page-structure/headings/).)
But there can be multiple examples of what to do with a (text or image) logo. I'm not sure recommending anything is helpful here.
I would treat the logo the same way you would treat text. The logo can be an image (with the `alt` parameter being the text) or just text. How you mark that up is not very important, as long as it makes sense. Again, using an `em` would not be wrong but it should be made clear that it's just an example.

## What is the 18F standard?

I found your [design standards](https://standards.usa.gov/components/headers/) which say the same thing about marking up the logo with an`em`. I wonder if it is an internal-only thing? If it is, I don't think it would belong here.

**Comment by nkkl** [comment]
This is a discussion we should escalate to the US Web Design System team; we're reinforcing their recommendation here _because_ they own the design system that we use internally. @maya who's the PM for USWDS?

> I wonder if it is an internal-only thing? If it is, I don't think it would belong here.

This guide is open to the public, but it's for 18F/TTS staff. The guide might benefit from slightly stronger language clarifying that (something for you to consider, @randyhart).

**Comment by maya** [comment]
@nkkl Thanks for the ping, but the USWDS note is based on the Accessibility Guide's recommendations. Let's fix it in the guide and we can both make any needed corrections. Also, they can open an issue for the USWDS documentation here: https://github.com/uswds/uswds-site.

**Comment by nkkl** [comment]
Interesting. Well, we can just run in circles, then! 😝 

Let's flag for a joint a11y guild and frontend guild discussion, then.

**Comment by maya** [comment]
>This confuses me because I interpret "the main heading of the page" as the page title. And usually there is no logo in that.

It's possible that the homepage uses the logo as the title of the page + h1. For example, DHS could have an image-based logo, but would want their page title + h1 to say "Department of Homeland Security" on the homepage. In that case, using a screen reader-only class on the h1 would work.

**Comment by mgwalker** [comment]
Closing as stale, on the assumption that the need will resurface if it still exists.

**Pull request closed without merging**
