### PR TITLE
Update the links and focus the sections

### PR DESCRIPTION
**Pull request by mgifford**
I thought it might be useful to adjust the links here a bit.  Let me know what you think.

### CODE REVIEW

**Comment by wslack** [comment]
@mgifford did you intend to remove the ARIA commentary? (trying to clean up the conflicting files)

**Comment by mgifford** [comment]
Hey @wslack I did a couple things. Sorry about the confusion. 

1) I created a section for World Wide Web Consortium's Web Accessibility Initiative and listed ARIA as a button within that. 

2) I removed the documentation. It was a bit inconsistent. Figured if folks weren't sure what it was they would click on the link. Maybe that's wrong.

3) I moved the CanIUse to be it's own thing and not specifically ARIA. It's really useful for HTML5 stuff too. 

4) I moved the practical examples of ARIA down to the bottom. 

So, mostly I moved things around and deleted the text description.

**Comment by nickbristow** [comment]
@mgifford can you resolve the conflicts? Then i'll merge. 

Thanks!

**Comment by mgifford** [comment]
I had the other links, but didn't seem to have the NZ standard. I added that back in:

* [CanIUse.com](http://caniuse.com/) - useful for HTML5, ARIA & CSS 
* [New Zealand Web Accessibility Standard 1.0 Assessment Guide](http://govtnz.github.io/web-standards/guidance/assessment-guides/web-a11y-standard-assessment-guide.html)

Hopefully that works.

**Pull request merged**
